export 'movies/movies_providers.dart';
export 'movies/movie_repository_provider.dart';
export 'movies/movies_slidershow_provider.dart';
export 'movies/initial_loading_provider.dart';
export 'movies/movie_info_provider.dart';
export 'actors/actors_provider.dart';
export 'actors/actors_repository_provider.dart';
export 'search/search_movie_provider.dart';
export 'storage/local_storage_provider.dart';
